title: 8AFYI
url: https://8a.fyi
author:
  name: information
  email: information@8a.fyi

remote_theme: jekyll/minima@d4d779a

plugins:
 - jekyll-feed
 - jekyll-seo-tag

header_pages:
  - tunes.md
  - emergency-emojis.md
  - quickreaction.html

minima:
  skin: auto
  show_excerpts: false
  date_format: "%b-%d-%Y"
  social_links:
    - title: 8a on bluesky
      icon: bluesky
      url: "https://bsky.app/profile/8a.fyi"
  hide_site_feed_link: true
