title: 8AFYI
url: https://8a.fyi
lang: en
author:
  name: information
  email: information@8a.fyi

plugins:
 - jekyll-feed
 - jekyll-seo-tag

header_pages:
  - emergency-emojis.md
  - quickreaction.md
  - text-to-image.html
  - jokes.md

social_links:
  - title: Bluesky
    url: "https://bsky.app/profile/8a.fyi"
